# Generated by Django 4.2.29 on 2026-03-09 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='姓名')),
                ('employee_id', models.CharField(max_length=32, unique=True, verbose_name='工号/学号')),
                ('face_encoding', models.JSONField(blank=True, null=True, verbose_name='人脸特征')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='persons/', verbose_name='照片')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='录入时间')),
            ],
            options={
                'verbose_name': '人员',
                'verbose_name_plural': '人员',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.DateTimeField(auto_now_add=True, verbose_name='签到时间')),
                ('source', models.CharField(default='web_camera', max_length=32, verbose_name='来源')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.person', verbose_name='签到人员')),
            ],
            options={
                'verbose_name': '考勤记录',
                'verbose_name_plural': '考勤记录',
                'ordering': ['-check_in_time'],
            },
        ),
    ]
