# Generated by Django 4.2.29 on 2026-03-10 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('normal', '正常'), ('late', '迟到')], default='normal', max_length=16, verbose_name='状态'),
        ),
    ]
