# Generated by Django 4.2.29 on 2026-03-10 23:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendance_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_deadline', models.TimeField(default=datetime.time(9, 0), help_text='此时间之后签到算迟到', verbose_name='签到截止时间')),
                ('allow_repeat', models.BooleanField(default=False, help_text='同一人同一天是否可重复签到', verbose_name='允许重复签到')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '考勤规则',
                'verbose_name_plural': '考勤规则',
            },
        ),
    ]
